create table RATES(
  MATURITY_PERIOD INTEGER PRIMARY KEY,
  INTEREST_RATE decimal(5,4),
  LAST_UPDATE datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP())
);

CREATE SEQUENCE "MY_SEQUENCE_NAME" 
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1 
START WITH 202700 
NOCACHE 
NOCYCLE;

create table CHECK_MORTAGE(
    ID INTEGER AUTO_INCREMENT PRIMARY KEY ,
  	MATURITY_PERIOD INTEGER NOT NULL,
    INCOME decimal(9,2),
  	LOAN_VALUE decimal(9,2),
  	HOME_VALUE decimal(9,2),
    FOREIGN KEY(MATURITY_PERIOD) REFERENCES RATES(MATURITY_PERIOD)
  
);